services:
  app:
    build:
      context: .
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./web/app:/var/www/html/web/app
      - ./config:/var/www/html/config
      - ./.env:/var/www/html/.env
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini  # <- Hier hoort hij thuis!
      - ./web/.htaccess:/var/www/html/web/.htaccess
    depends_on:
      - db

  db:
    image: mariadb:11.4
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: